# config.yaml - Sample configuration file

app:
  name: MyApplication
  version: 1.0.0
  environment: production

database:
  host: localhost
  port: 8000
  username: admin
  password: secret123

logging:
  level: INFO
  file: /var/log/myapp.log

features:
  - authentication
  - monitoring
  - backups

